Revert "-fno-operator-names causes build failure for me because of either GCC9 or new Boost"
This reverts commit da6aa3c1c6b48be00e2a1a1d5e604b3a19bac178.

Causes other build failures:

In file included from /var/tmp/portage/dev-php/hhvm-3.30.12-r5/work/hhvm-3.30.12/hphp/util/asm-x64.cpp:16:
/var/tmp/portage/dev-php/hhvm-3.30.12-r5/work/hhvm-3.30.12/hphp/util/asm-x64.h:942:8: error: expected unqualified-id before 'not' token
  942 |   void not(Reg64 r)   { instrR(instr_not,  r); }
      |        ^~~